name: lstmcpipe
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.7
  - astropy~=4.2
  - pip
  - pre-commit
  - ctapipe==0.12
  - ruamel.yaml>=0.17
  - protobuf=3.20
  - protozfits=2.0  # necessary to be here, or tries to be installed from pypi and fails
  - pip:
      - ctaplot
      - ctapipe_io_lst
      - lstchain>=0.9.7
      - pyirf~=0.6.0
      - eventio<1.11.0
